### ISSUE TITLE
Support for new version of Silero VAD

### ISSUE THREAD

**Issue by shaircast** [char5742/flutter_silero_vad#12]
Silero VAD V5 has been released recently. Any plans to support it?
I tested with the new version in iOS yesterday and sadly it crashed.

**Comment by char5742** [comment]
Thank you for informing me. 
I have work commitments during the weekdays, so I plan to address this issue over the next weekend.

**Comment by char5742** [comment]
The update to support Silero VAD V5 has been completed.
