### ISSUE TITLE
How to train model Silero VAD? 

### ISSUE THREAD

**Issue by ITHealer** [char5742/flutter_silero_vad#3]
Can you share with me about how to train or pretrain model silero VAD?

**Comment by char5742** [comment]
Currently, my library is utilizing the [pre-trained models](https://github.com/snakers4/silero-vad/tree/master/files) provided by Silero VAD . For information on the training methods of these models, I recommend referring to the [documentation](https://github.com/snakers4/silero-vad) and source code published by the developers of Silero VAD.

**Comment by ITHealer** [comment]
> Currently, my library is utilizing the [pre-trained models](https://github.com/snakers4/silero-vad/tree/master/files) provided by Silero VAD . For information on the training methods of these models, I recommend referring to the [documentation](https://github.com/snakers4/silero-vad) and source code published by the developers of Silero VAD.

Thanks!
