### ISSUE TITLE
The app crashes when tapping the 'Start' button on the example - Flutter iOS device.

### ISSUE THREAD

**Issue by zxl777** [char5742/flutter_silero_vad#6]
`await ref.read(audioServiceProvider).play();`

Error configuring audio session

<img width="1400" alt="image" src="https://github.com/char5742/flutter_silero_vad/assets/816448/a2eafe75-f1d7-42fb-82dd-7d4a0461a155">

**Comment by char5742** [comment]
Thank you for bringing this issue to our attention.I have addressed and resolved it in the latest commit. You can review the changes [here](https://github.com/char5742/flutter_silero_vad/commit/93d308935761b103bc73aaa75e7e879b8aa93075#): https://github.com/char5742/flutter_silero_vad/blob/93d308935761b103bc73aaa75e7e879b8aa93075/example/lib/services/audio.dart#L15-L17
Please let me know if there are any further issues or concerns.

**Comment by zxl777** [comment]
I've tested the latest commit on an iPhone 12 mini running iOS 17.2.1. Now, I can tap the Start button to replay my sound. However, when I try to say "1 [pause] 2 [pause] 3 [pause] 4 [pause] 5 [pause] 6 [pause] 7 [pause] 8," the playback is inconsistent. Sometimes I can hear "1 2 3 4 5," and at other times, I only hear "6 7 8." The sound playback is not complete. #7 

Additionally, I encountered a crash, as shown in the attached screenshot.

<img width="1662" alt="image" src="https://github.com/char5742/flutter_silero_vad/assets/816448/81c347b6-a5cb-4396-9d62-cb4d4b291fff">

**Comment by char5742** [comment]
I have also confirmed this issue on my end. However, I have not yet identified the specific problem area. Please wait a while as I continue to investigate.

**Comment by zxl777** [comment]
Thank you, I will test it as soon as the issue is resolved.

I hope to use this module for all-day recording, followed by transcription, for the purpose of learning a second language. 
Therefore, complete segment recordings are important. 
Additionally, energy consumption needs to be considered.

**Comment by char5742** [comment]
The bug has been identified; it's on the playback side. Currently, we're using audioplayers, but changing the file storage to 'document' and playing directly from the iPhone's file app results in all audio playing without issue.

If you wish to use it for transcription, there's no need to play it directly with audioplayers, right? With the path_provider library, you can save the recording file to an easily accessible location from the file app as follows:

```
String outputPath =
          '${(await getApplicationDocumentsDirectory()).path}/output.wav';
```

**Comment by zxl777** [comment]
I've figured out the issue. When I recite "ABCDEFGHIJK" aloud, the recording is perfect. However, when I say "1, 2, 3, 4, 5, 6, 7, 8, 9, 10" in Chinese, only the sound of "10" is captured.
